---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: immich-media
  namespace: immich
spec:
  sourcePVC: immich-media
  trigger:
    schedule: "30 3 * * *" # at 4:30
  rclone:
    rcloneConfigSection: "s3-bucket"
    rcloneDestPath: "prod-backup/immich/immich-media"
    rcloneConfig: "volsync-secret"
    copyMethod: Clone
    volumeSnapshotClassName: csi-cephfsplugin-snapshotclass
