---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich
  namespace: immich
data:
  immich.json: |-
    {
      "ffmpeg": {
        "crf": 23,
        "threads": 0,
        "preset": "ultrafast",
        "targetVideoCodec": "h264",
        "acceptedVideoCodecs": [
          "h264"
        ],
        "targetAudioCodec": "aac",
        "acceptedAudioCodecs": [
          "aac",
          "mp3",
          "libopus"
        ],
        "targetResolution": "720",
        "maxBitrate": "0",
        "bframes": -1,
        "refs": 0,
        "gopSize": 0,
        "npl": 0,
        "temporalAQ": false,
        "cqMode": "auto",
        "twoPass": false,
        "preferredHwDevice": "auto",
        "transcode": "required",
        "tonemap": "hable",
        "accel": "disabled"
      },
      "job": {
        "backgroundTask": {
          "concurrency": 5
        },
        "smartSearch": {
          "concurrency": 2
        },
        "metadataExtraction": {
          "concurrency": 5
        },
        "faceDetection": {
          "concurrency": 2
        },
        "search": {
          "concurrency": 5
        },
        "sidecar": {
          "concurrency": 5
        },
        "library": {
          "concurrency": 5
        },
        "migration": {
          "concurrency": 5
        },
        "thumbnailGeneration": {
          "concurrency": 5
        },
        "videoConversion": {
          "concurrency": 1
        }
      },
      "logging": {
        "enabled": true,
        "level": "log"
      },
      "machineLearning": {
        "enabled": true,
        "url": "http://immich-machine-learning:3003",
        "clip": {
          "enabled": true,
          "modelName": "ViT-B-32__openai"
        },
        "facialRecognition": {
          "enabled": true,
          "modelName": "buffalo_l",
          "minScore": 0.7,
          "maxDistance": 0.5,
          "minFaces": 3
        }
      },
      "map": {
        "enabled": true,
        "lightStyle": "",
        "darkStyle": ""
      },
      "reverseGeocoding": {
        "enabled": true
      },
      "oauth": {
        "autoLaunch": false,
        "autoRegister": true,
        "buttonText": "Login with OAuth",
        "clientId": "",
        "clientSecret": "",
        "enabled": false,
        "issuerUrl": "",
        "mobileOverrideEnabled": false,
        "mobileRedirectUri": "",
        "scope": "openid email profile immichscope",
        "signingAlgorithm": "RS256",
        "storageLabelClaim": "preferred_username",
        "storageQuotaClaim": "immichquota"
      },
      "passwordLogin": {
        "enabled": true
      },
      "storageTemplate": {
        "enabled": true,
        "hashVerificationEnabled": true,
        "template": "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
      },
      "thumbnail": {
        "webpSize": 250,
        "jpegSize": 1440,
        "quality": 80,
        "colorspace": "p3"
      },
      "newVersionCheck": {
        "enabled": true
      },
      "trash": {
        "enabled": true,
        "days": 30
      },
      "theme": {
        "customCss": ""
      },
      "library": {
        "scan": {
          "enabled": true,
          "cronExpression": "0 0 * * *"
        },
        "watch": {
          "enabled": false
        }
      },
      "server": {
        "externalDomain": "",
        "loginPageMessage": ""
      },
      "user": {
        "deleteDelay": 7
      }
    }
