---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - navidrome-ns.yaml
  - navidrome-svc.yaml
  - navidrome-pvc.yaml
  - navidrome-deployment.yaml
  - navidrome-virtualservice.yaml
  - navidrome-authpolicy.yaml
  - filebrowser.yaml
  - beets.yaml
