apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openspeedtest-ns.yaml
  - openspeedtest-deployment.yaml
  - openspeedtest-virtualservice.yaml
  - openspeedtest-authpolicy.yaml
